### ISSUE TITLE
Unable to find service

### ISSUE THREAD

**Issue by themaluxis** [popeen/Home-Assistant-Custom-Component-TCL-Remote#1]
Hey dude, thanks for your integration.
I tried to install it via HACS, once installed I tried to use it before and after a reboot. In both case, HA is unable to find the service. Any idea ? 
<img width="1440" alt="Capture d’écran 2023-01-15 à 11 33 01" src="https://user-images.githubusercontent.com/2593413/212535809-054e11a8-f5be-4ce3-aa36-eb90be6f2dd0.png">

**Comment by popeen** [comment]
Ah sorry, I had forgotten to include a step in the documentation. To register the service you need to add the following to your configuration.yaml file, then restart Home Assistant

`tcl_tv_remote:`

**Comment by themaluxis** [comment]
Thanks, working like a charm :)

**Comment by popeen** [comment]
Awesome! :)
