### ISSUE TITLE
My TCL TV uses Android system

### ISSUE THREAD

**Issue by PleasecallmeME** [popeen/Home-Assistant-Custom-Component-TCL-Remote#2]
How can I use HSS to switch on and off TV?

**Comment by popeen** [comment]
I haven't looked in to it to much as I don't have an Android TV but you can probably turn it off using adb
https://www.home-assistant.io/integrations/androidtv/

Turning it on might be a bit more complicated as the TV needs to be turned on to receive the commands, the plan for my personal TV is to build an IR remote using ESPHome.
https://esphome.io/components/remote_transmitter.html

As this component isn't for Android TV I will close the issue
