### ISSUE TITLE
Question: Where to find the Keycodes?

### ISSUE THREAD

**Issue by mokrates** [popeen/Home-Assistant-Custom-Component-TCL-Remote#4]
I have a TV which responds to this kind of remote control. One button I would use, though, is the one to open the source menu (to choose hdmi1-3, AV or tuner). None of the key codes in your list seem to work, though.

Google didn't really help me (I just found another github project implementing this with a different frontend), so I try it this way:

Can you tell me where you found this codes? Is there a spec or a firmware one can get these codes out of?

Thanks

**Comment by popeen** [comment]
Unfortunately I don't remember where I originally got them.

Most likely I sniffed the traffic of my phone while using an app but I am not sure about that.
