### ISSUE TITLE
Click this button to add it using config flow

### ISSUE THREAD

**Issue by Sincere74** [popeen/Home-Assistant-Custom-Component-TCL-Remote#5]
![image](https://github.com/popeen/Home-Assistant-Custom-Component-TCL-Remote/assets/151158573/643740a4-de10-487a-aec8-4da4f32fc15e)

![image](https://github.com/popeen/Home-Assistant-Custom-Component-TCL-Remote/assets/151158573/d3e9ec4e-15bb-4b78-8bef-6fa4d3de5a8a)

**Comment by popeen** [comment]
Older versions of the integration did not support config flow setup. Make sure you have version 0.1.3+ installed and it should work.
